version: 2.1

jobs:
  build:
    working_directory: ~/project
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: install
          command: npm ci --ignore-engines
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
            - ~/.cache/Cypress
      - persist_to_workspace:
          root: ~/
          paths:
            - project/node_modules
            - .cache
            - cypress/*

  lint:
    working_directory: ~/project
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - attach_workspace:
          at: ~/
      - run:
          name: lint
          command: npm run lint

  test:
    working_directory: ~/project
    docker:
      - image: circleci/node:8.12.0-browsers
    steps:
      - checkout
      - attach_workspace:
          at: ~/
      - run:
          name: test
          command: npm run test
      - run:
          name: coverage
          command: npx codecov

  release:
    working_directory: ~/project
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - attach_workspace:
          at: ~/
      - run:
          name: release
          command: npm run semantic-release

workflows:
  version: 2.1
  project:
    jobs:
      - build
      - lint:
          requires:
            - build
      - test:
          requires:
            - lint
      - release:
          filters:
            branches:
              only:
                - master
          requires:
            - lint
